[package]
name = "ctp_fantasy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2.1.0", features = ["postgres"] }
dotenvy = "0.15"
reqwest = { version = "0.11.20", features = ["json"] }
tokio = { version = "1.32.0", features = ["full"] }
serde = "1.0.186"
serde_derive = "1.0.186"
serde_json = "1.0.105"
sea-orm = { version = "0.12", features = [ "sqlx-postgres", "runtime-tokio-rustls", "macros" ] }
entity = { path = "./entity" }
migration = { path = "./migration" }
itertools = "0.12.0"

[workspace]
members = [".", "entity", "migration"]
