[package]
name = "dto"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "dto"
path = "src/lib.rs"

[dependencies]
rocket = { version = "0.5.0-rc.4", features = ["json", "serde_json"] }
sea-orm = "0.12.10"
entity = { path = "../entity" }
rocket_okapi = "0.8.0"