# curl -X 'GET'
#  'http://localhost:8000/api/check-cookie'
#
#  -H 'accept: application/json'
#  -H 'Cookie: auth=zYKuaUjVBfRHYEZhGyMOD5SIMmOMd4; Secure'
PUT http://192.170.122.114:8000/api/fantasy-tournament/1/user/1/slot/1/8332
accept: application/json
Cookie: auth=xsDKLbLE7hyX6GJeg4cqPWNuuOS5L7; Secure

###

