# curl -X 'GET'
#  'http://localhost:8000/api/check-cookie'
#
#  -H 'accept: application/json'
#  -H 'Cookie: auth=zYKuaUjVBfRHYEZhGyMOD5SIMmOMd4; Secure'
POST 127.0.0.1:8000/api/fantasy-tournament/1/force-refresh
accept: application/json
Cookie: auth=SVTaTEtMJWvvv4Hjq35iZEurMs3kVl; Secure

###

