//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;
use serde::Deserialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize)]
#[sea_orm(table_name = "fantasy_scores")]
#[serde(rename_all = "PascalCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user: i32,
    pub fantasy_tournament_id: i32,
    pub score: i32,
    pub round_score_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::competition::Entity",
        from = "Column::FantasyTournamentId",
        to = "super::competition::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Competition,
    #[sea_orm(
        belongs_to = "super::fantasy_tournament::Entity",
        from = "Column::FantasyTournamentId",
        to = "super::fantasy_tournament::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    FantasyTournament,
    #[sea_orm(
        belongs_to = "super::player_round_score::Entity",
        from = "Column::RoundScoreId",
        to = "super::player_round_score::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PlayerRoundScore,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::User",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User,
}

impl Related<super::competition::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Competition.def()
    }
}

impl Related<super::fantasy_tournament::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FantasyTournament.def()
    }
}

impl Related<super::player_round_score::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlayerRoundScore.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
