//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "phantom_competition_in_fantasy_tournament")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub fantasy_tournament_id: i32,
    pub phantom_competition_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::fantasy_tournament::Entity",
        from = "Column::FantasyTournamentId",
        to = "super::fantasy_tournament::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    FantasyTournament,
    #[sea_orm(
        belongs_to = "super::phantom_competition::Entity",
        from = "Column::PhantomCompetitionId",
        to = "super::phantom_competition::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    PhantomCompetition,
}

impl Related<super::fantasy_tournament::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FantasyTournament.def()
    }
}

impl Related<super::phantom_competition::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PhantomCompetition.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
