//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;
use serde::Deserialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize)]
#[sea_orm(table_name = "phantom_competition")]
#[serde(rename_all = "PascalCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub name: String,
    pub date: Date,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::phantom_competition_in_fantasy_tournament::Entity")]
    PhantomCompetitionInFantasyTournament,
}

impl Related<super::phantom_competition_in_fantasy_tournament::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PhantomCompetitionInFantasyTournament.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
