//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use super::sea_orm_active_enums::Division;
use sea_orm::entity::prelude::*;
use serde::Deserialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize)]
#[sea_orm(table_name = "player_round_score")]
#[serde(rename_all = "PascalCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub pdga_number: i32,
    pub competition_id: i32,
    pub round: i32,
    pub score: i32,
    pub division: Division,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::competition::Entity",
        from = "Column::CompetitionId",
        to = "super::competition::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Competition,
    #[sea_orm(has_many = "super::fantasy_scores::Entity")]
    FantasyScores,
    #[sea_orm(
        belongs_to = "super::player::Entity",
        from = "Column::PdgaNumber",
        to = "super::player::Column::PdgaNumber",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Player,
}

impl Related<super::competition::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Competition.def()
    }
}

impl Related<super::fantasy_scores::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FantasyScores.def()
    }
}

impl Related<super::player::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Player.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
