//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;
use serde::Deserialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize)]
#[sea_orm(table_name = "player")]
#[serde(rename_all = "PascalCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub pdga_number: i32,
    pub first_name: String,
    pub last_name: String,
    pub avatar: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::fantasy_pick::Entity")]
    FantasyPick,
    #[sea_orm(has_many = "super::player_division::Entity")]
    PlayerDivision,
    #[sea_orm(has_many = "super::player_in_competition::Entity")]
    PlayerInCompetition,
    #[sea_orm(has_many = "super::player_round_score::Entity")]
    PlayerRoundScore,
}

impl Related<super::fantasy_pick::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FantasyPick.def()
    }
}

impl Related<super::player_division::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlayerDivision.def()
    }
}

impl Related<super::player_in_competition::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlayerInCompetition.def()
    }
}

impl Related<super::player_round_score::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlayerRoundScore.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
