//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

pub use super::fantasy_tournament::Entity as FantasyTournament;
pub use super::player::Entity as Player;
pub use super::player_division::Entity as PlayerDivision;
pub use super::player_in_tournament::Entity as PlayerInTournament;
pub use super::tournament::Entity as Tournament;
pub use super::user::Entity as User;
