//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use super::sea_orm_active_enums::TournamentStatus;
use sea_orm::entity::prelude::*;
use serde::Deserialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize)]
#[sea_orm(table_name = "tournament")]
#[serde(rename_all = "PascalCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub status: TournamentStatus,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::player_in_tournament::Entity")]
    PlayerInTournament,
}

impl Related<super::player_in_tournament::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlayerInTournament.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
